### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by georgeneil** [tripti825/react-boilerplate_AdminLTE#1]
$ npm run setup

> react-boilerplate@3.5.0 presetup G:\react-boilerplate_AdminLTE
> npm i chalk shelljs

react-boilerplate@3.5.0 G:\react-boilerplate_AdminLTE
+-- chalk@1.1.3
`-- shelljs@0.7.8

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch                                                                                                                                                                                               okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                                                                                                               1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                                                                                                                                                               )

> react-boilerplate@3.5.0 setup G:\react-boilerplate_AdminLTE
> node ./internals/scripts/setup.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'G:\react-boilerplate_AdminLTE\internals\sc                                                                                                                                                                                               ripts\setup.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                                                                                               node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.5.0 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.5.0 setup script 'node ./internals/sc                                                                                                                                                                                               ripts/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate pac                                                                                                                                                                                               kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\react-boilerplate_AdminLTE\npm-debug.log

**Comment by tripti825** [comment]
hello @georgeneil , this is an issue with the react-boilerplate itself, which even I have posted in their forum =>
https://github.com/react-boilerplate/react-boilerplate/issues/2142

To solve it (for now), 
1. Delete the previous project folder you cloned/downloaded and clone/download a fresh copy now.
   `git clone https://github.com/tripti825/react-boilerplate_AdminLTE` or simply download.

2. Go to the project folder and run command `npm run setup`. [here is the where the issue is, the setup.js file from internals/scripts/ gets deleted]

3. Go to https://github.com/tripti825/react-boilerplate_AdminLTE/tree/master/internals/scripts and copy the setup.js file in your project folder in the same  and run `npm run build:dll` command. 

4. Run command `npm run build:dll`

Until the official team comments on the same, I can provide no further solution to this.
